# Generated by Django 5.0.7 on 2024-10-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('referencia_pk', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('accesorios', models.CharField(blank=True, max_length=1000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_consulta', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Referencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('referencia_pk', models.OneToOneField(db_column='referencia_pk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='references.referencias')),
                ('imagen_1', models.ImageField(blank=True, default='default/image_none.jpg', max_length=400, null=True, upload_to='References_pictures/')),
                ('imagen_2', models.ImageField(blank=True, default='default/image_none.jpg', max_length=400, null=True, upload_to='References_pictures/')),
                ('imagen_3', models.ImageField(blank=True, default='default/image_none.jpg', max_length=400, null=True, upload_to='References_pictures/')),
                ('imagen_4', models.ImageField(blank=True, default='default/image_none.jpg', max_length=400, null=True, upload_to='References_pictures/')),
                ('imagen_5', models.ImageField(blank=True, default='default/image_none.jpg', max_length=400, null=True, upload_to='References_pictures/')),
                ('ficha_tecnica', models.FileField(blank=True, max_length=400, null=True, upload_to='technical_sheets/')),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
    ]
