# Generated by Django 5.0.7 on 2024-10-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categoriascampo_campo_fk_and_more'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, max_length=500, null=True)),
                ('campo_fk', models.ForeignKey(blank=True, db_column='campo_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.campo')),
                ('referencia_fk', models.ForeignKey(blank=True, db_column='referencia_fk', max_length=250, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.referencias')),
            ],
            options={
                'db_table': 'valor',
            },
        ),
    ]
