# Generated by Django 5.0.7 on 2024-10-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor',
            name='id_pk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
