# Generated by Django 5.0.7 on 2024-10-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_alter_valor_campo_fk_alter_valor_referencia_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencias',
            name='referencia_pk',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
