# Generated by Django 5.0.7 on 2024-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_alter_referencias_referencia_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='imagen_1',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='References_pictures/'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='imagen_2',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='References_pictures/'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='imagen_3',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='References_pictures/'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='imagen_4',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='References_pictures/'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='imagen_5',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='References_pictures/'),
        ),
    ]
