# Generated by Django 5.0.7 on 2024-10-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categoriascampo_campo_fk_and_more'),
        ('references', '0006_alter_archivos_imagen_1_alter_archivos_imagen_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='referencia_pk',
            field=models.OneToOneField(db_column='referencia_pk', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='references.referencias'),
        ),
        migrations.AlterField(
            model_name='referencias',
            name='categoria',
            field=models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.CASCADE, to='categories.categorias'),
        ),
    ]
