# Generated by Django 5.0.7 on 2024-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_alter_archivos_referencia_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor',
            name='valor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
