# Generated by Django 5.0.7 on 2024-10-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth',
        ),
    ]
