# Generated by Django 5.0.7 on 2024-10-04 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=6)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('CATEGORIA', 'Categoría'), ('EQUIPO', 'Equipo'), ('EXISTENCIA', 'Existencia'), ('INTERVENCION', 'Intervención'), ('USUARIO_PERFIL', 'Usuario/Perfil'), ('PIEZA', 'Pieza')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
