# Generated by Django 5.0.7 on 2024-10-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('EDIT', 'Editar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar sesión'), ('LOCKOUT', 'Bloquear')], max_length=25),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(blank=True, choices=[('CATEGORY', 'Categoría'), ('TEAMS', 'Equipo'), ('STOCKS', 'Existencia'), ('INTERVENTIONS', 'Intervención'), ('USER_PROFILE', 'Usuario/Perfil'), ('PART', 'Pieza')], max_length=20, null=True),
        ),
    ]
