# Generated by Django 5.0.7 on 2024-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='title',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
