# Generated by Django 5.0.7 on 2024-12-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0003_remove_activitylog_title_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
