# Generated by Django 5.0.7 on 2024-12-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0004_activitylog_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='visible',
        ),
    ]
