# Generated by Django 5.0.7 on 2024-10-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizaciones',
            fields=[
                ('actualizacion_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'actualizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('referencia_pk', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('accesorios', models.CharField(blank=True, max_length=1000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_consulta', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('campo_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'campo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriasCampo',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categorias_campo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('cod_equipo_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=250)),
                ('estado', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'existencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('num_orden_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.IntegerField(blank=True, null=True)),
                ('procesador', models.CharField(blank=True, max_length=400, null=True)),
                ('tarea_realizada', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('formato', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'intervenciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('num_parte_pk', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('link_consulta', models.CharField(blank=True, max_length=1000, null=True)),
                ('manual', models.CharField(blank=True, max_length=400, null=True)),
                ('total_unidades', models.IntegerField()),
                ('imagen_1', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_2', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_3', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_4', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_5', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'valor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('referencia_pk', models.OneToOneField(db_column='referencia_pk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='logIn.equipos')),
                ('imagen_1', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_2', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_3', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_4', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen_5', models.CharField(blank=True, max_length=400, null=True)),
                ('ficha_tecnica', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('referencia_pk', models.OneToOneField(db_column='referencia_pk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='logIn.equipos')),
                ('tipo_procesador', models.CharField(blank=True, max_length=400, null=True)),
                ('memoria_ram', models.CharField(blank=True, max_length=400, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=400, null=True)),
                ('des_pantalla', models.CharField(blank=True, max_length=400, null=True)),
                ('puertos_fisicos_externos', models.CharField(blank=True, max_length=1000, null=True)),
                ('puertos_fisicos_internos', models.CharField(blank=True, max_length=1000, null=True)),
                ('tarjeta_video', models.CharField(blank=True, max_length=400, null=True)),
                ('consumible', models.CharField(blank=True, max_length=400, null=True)),
                ('des_videobean', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'componentes',
                'managed': False,
            },
        ),
    ]
