# Generated by Django 5.0.7 on 2024-10-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actualizaciones',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='referencia_pk',
        ),
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='CategoriasCampo',
        ),
        migrations.RemoveField(
            model_name='componentes',
            name='referencia_pk',
        ),
        migrations.DeleteModel(
            name='Existencias',
        ),
        migrations.DeleteModel(
            name='Intervenciones',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.DeleteModel(
            name='Componentes',
        ),
        migrations.DeleteModel(
            name='Equipos',
        ),
    ]
