# Generated by Django 5.0.7 on 2024-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0002_remove_customuser_age_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
