# Generated by Django 5.0.7 on 2024-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='imagen_1',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='Parts_pictures/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='imagen_2',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='Parts_pictures/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='imagen_3',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='Parts_pictures/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='imagen_4',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='Parts_pictures/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='imagen_5',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='Parts_pictures/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='link_consulta',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='manual',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='technical_sheets/'),
        ),
    ]
