# Generated by Django 5.0.7 on 2024-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsInventory', '0002_alter_inventario_imagen_1_alter_inventario_imagen_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='total_unidades',
            field=models.IntegerField(default=0),
        ),
    ]
