# Generated by Django 5.0.7 on 2024-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsInventory', '0003_alter_inventario_total_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='link_compra_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='inventario',
            name='link_compra_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='inventario',
            name='link_compra_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
