# Generated by Django 5.0.7 on 2024-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsInventory', '0005_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
