# Generated by Django 5.0.7 on 2024-12-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsInventory', '0006_compras_color_alter_compras_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
