# Generated by Django 5.0.7 on 2025-01-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsInventory', '0007_delete_compras'),
        ('references', '0008_alter_valor_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezasReferencias',
            fields=[
                ('id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('num_parte_fk', models.ForeignKey(db_column='num_parte_fk', on_delete=django.db.models.deletion.CASCADE, to='partsInventory.inventario')),
                ('referencia_fk', models.ForeignKey(db_column='referencia_fk', on_delete=django.db.models.deletion.CASCADE, to='references.referencias')),
            ],
            options={
                'db_table': 'piezas_referencias',
            },
        ),
    ]
