# Generated by Django 5.0.7 on 2024-12-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partsInventory', '0007_delete_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('num_parte_fk', models.ForeignKey(db_column='num_parte_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='partsInventory.inventario')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
    ]
