# Generated by Django 5.0.7 on 2024-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compras',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
