# Generated by Django 5.0.7 on 2024-10-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('partsInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('num_orden_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.IntegerField(blank=True, null=True)),
                ('procesador', models.CharField(blank=True, max_length=400, null=True)),
                ('tarea_realizada', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('formato', models.CharField(blank=True, max_length=400, null=True)),
                ('cod_equipo_fk', models.ForeignKey(db_column='cod_equipo_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.equipos')),
            ],
            options={
                'db_table': 'intervenciones',
            },
        ),
        migrations.CreateModel(
            name='Actualizaciones',
            fields=[
                ('actualizacion_pk', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('num_parte_fk', models.ForeignKey(blank=True, db_column='num_parte_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partsInventory.inventario')),
                ('num_orden_fk', models.ForeignKey(db_column='num_orden_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='inserts.intervenciones')),
            ],
            options={
                'db_table': 'actualizaciones',
            },
        ),
    ]
