# Generated by Django 5.0.7 on 2024-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizaciones',
            fields=[
                ('actualizacion_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'actualizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('num_orden_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.IntegerField(blank=True, null=True)),
                ('procesador', models.CharField(blank=True, max_length=400, null=True)),
                ('tarea_realizada', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('formato', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'intervenciones',
                'managed': False,
            },
        ),
    ]
