# Generated by Django 5.0.7 on 2024-11-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0001_initial'),
        ('partsInventory', '0002_alter_inventario_imagen_1_alter_inventario_imagen_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizaciones',
            name='accion',
        ),
        migrations.AddField(
            model_name='actualizaciones',
            name='fuente',
            field=models.CharField(choices=[('intervencion', 'Intervención'), ('compra', 'Compra'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AddField(
            model_name='actualizaciones',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actualizaciones',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('espera', 'Espera')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='cantidad',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='num_orden_fk',
            field=models.ForeignKey(blank=True, db_column='num_orden_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inserts.intervenciones'),
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='num_parte_fk',
            field=models.ForeignKey(db_column='num_parte_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='partsInventory.inventario'),
        ),
    ]
