# Generated by Django 5.0.7 on 2024-11-08 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0002_remove_actualizaciones_accion_actualizaciones_fuente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenciones',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='intervenciones',
            name='usuario_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
