# Generated by Django 5.0.7 on 2024-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0003_remove_intervenciones_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizaciones',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='fuente',
            field=models.CharField(max_length=100),
        ),
    ]
