# Generated by Django 5.0.7 on 2024-11-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0004_actualizaciones_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervenciones',
            old_name='usuario_fk',
            new_name='usuario_fk_id',
        ),
    ]
