# Generated by Django 5.0.7 on 2024-11-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0005_rename_usuario_fk_intervenciones_usuario_fk_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervenciones',
            old_name='usuario_fk_id',
            new_name='usuario_fk',
        ),
    ]
