# Generated by Django 5.0.7 on 2024-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0007_intervenciones_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenciones',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='intervenciones',
            name='formato',
            field=models.FileField(blank=True, null=True, upload_to='intervenciones_pdfs/'),
        ),
    ]
