# Generated by Django 5.0.7 on 2024-11-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0008_remove_intervenciones_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenciones',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
