# Generated by Django 5.0.7 on 2024-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0009_intervenciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenciones',
            name='formato',
            field=models.FileField(blank=True, null=True, upload_to='interventions_pdfs/'),
        ),
    ]
