# Generated by Django 5.0.7 on 2024-12-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_alter_equipos_referencia_fk'),
        ('inserts', '0010_alter_intervenciones_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenciones',
            name='cod_equipo_fk',
            field=models.ForeignKey(db_column='cod_equipo_fk', on_delete=django.db.models.deletion.CASCADE, to='equipments.equipos'),
        ),
    ]
