# Generated by Django 5.0.7 on 2024-12-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserts', '0011_alter_intervenciones_cod_equipo_fk'),
        ('partsInventory', '0004_inventario_link_compra_1_inventario_link_compra_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenciones',
            name='procesador',
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='num_orden_fk',
            field=models.ForeignKey(blank=True, db_column='num_orden_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='inserts.intervenciones'),
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='num_parte_fk',
            field=models.ForeignKey(db_column='num_parte_fk', on_delete=django.db.models.deletion.CASCADE, to='partsInventory.inventario'),
        ),
    ]
