# Generated by Django 5.0.7 on 2024-10-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('campo_pk', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'campo',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(default='default/default.jpg', upload_to='categories_pictures/')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='CategoriasCampo',
            fields=[
                ('id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('campo_fk', models.ForeignKey(db_column='campo_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='categories.campo')),
                ('categoria_fk', models.ForeignKey(db_column='categoria_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categorias')),
            ],
            options={
                'db_table': 'categorias_campo',
            },
        ),
    ]
