# Generated by Django 5.0.7 on 2024-10-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('referencia_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campos', models.JSONField()),
                ('imagen', models.ImageField(blank=True, max_length=400, null=True, upload_to='categories/')),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
    ]
