# Generated by Django 5.0.7 on 2024-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('campo_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'campo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='categories_pictures/')),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriasCampo',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categorias_campo',
                'managed': False,
            },
        ),
    ]
