# Generated by Django 5.0.7 on 2024-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='campo_pk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
