# Generated by Django 5.0.7 on 2024-10-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_campo_campo_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriascampo',
            name='campo_fk',
            field=models.ForeignKey(db_column='campo_fk', on_delete=django.db.models.deletion.CASCADE, to='categories.campo'),
        ),
        migrations.AlterField(
            model_name='categoriascampo',
            name='categoria_fk',
            field=models.ForeignKey(db_column='categoria_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.categorias'),
        ),
    ]
