# Generated by Django 5.0.7 on 2024-10-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('cod_equipo_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=250)),
                ('estado', models.CharField(blank=True, max_length=250, null=True)),
                ('referencia_fk', models.ForeignKey(db_column='referencia_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='references.referencias')),
            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, max_length=45, null=True)),
                ('campo_fk', models.ForeignKey(blank=True, db_column='campo_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.campo')),
                ('referencia_fk', models.ForeignKey(blank=True, db_column='referencia_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.referencias')),
            ],
            options={
                'db_table': 'valor',
            },
        ),
    ]
