# Generated by Django 5.0.7 on 2024-10-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Valor',
        ),
    ]
