# Generated by Django 5.0.7 on 2024-10-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_delete_valor'),
        ('references', '0006_alter_archivos_imagen_1_alter_archivos_imagen_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='referencia_fk',
            field=models.ForeignKey(db_column='referencia_fk', on_delete=django.db.models.deletion.CASCADE, to='references.referencias'),
        ),
    ]
