# Generated by Django 5.0.7 on 2025-01-03 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('descripcion', models.TextField(max_length=500)),
                ('completado', models.BooleanField(default=False)),
                ('usuario_fk', models.ForeignKey(blank=True, db_column='usuario_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
