# Generated by Django 5.0.7 on 2025-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_metas_descripcion_metas_rango_fechas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
    ]
